language: objective-c
osx_image: xcode8
env:
    - DESTINATION="OS=10.0,name=iPhone 6" SCHEME="EKRecurrenceRuleStringExtension" SDK="iphonesimulator10.0"
before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -project EKRecurrenceRuleStringExtension.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
